package server

import (
	"context"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/FAIRmat-NFDI/nomad-storage-gateway/internal/config"
	"github.com/aws/aws-sdk-go-v2/aws"
	v4 "github.com/aws/aws-sdk-go-v2/aws/signer/v4"
	"github.com/seaweedfs/seaweedfs/weed/pb/filer_pb"
)

type signOptions struct {
	accessKey       string
	secretKey       string
	region          string
	signingTime     time.Time
	expires         time.Duration
	rawQueryMutator func(url.Values)
}

func buildSignedRequest(t *testing.T, cfg config.Config, method, requestPath string, opts signOptions) *http.Request {
	t.Helper()

	accessKey := opts.accessKey
	if accessKey == "" {
		accessKey = cfg.SeaweedFS.S3AccessKey
	}
	secretKey := opts.secretKey
	if secretKey == "" {
		secretKey = cfg.SeaweedFS.S3SecretKey
	}
	region := opts.region
	if region == "" {
		region = "us-east-1"
	}
	signingTime := opts.signingTime
	if signingTime.IsZero() {
		signingTime = time.Now().UTC()
	}
	expires := opts.expires
	if expires == 0 {
		expires = 15 * time.Minute
	}

	publicURL, err := url.Parse(cfg.SeaweedFS.PublicEndpoint)
	if err != nil {
		t.Fatalf("parse public endpoint: %v", err)
	}

	u := *publicURL
	u.Path = strings.TrimSuffix(publicURL.Path, "/") + requestPath
	q := u.Query()
	q.Set("X-Amz-Expires", strconv.FormatInt(int64(expires.Seconds()), 10))
	u.RawQuery = q.Encode()

	req, err := http.NewRequest(method, u.String(), nil)
	if err != nil {
		t.Fatalf("new request: %v", err)
	}

	signer := v4.NewSigner(func(o *v4.SignerOptions) {
		o.DisableURIPathEscaping = true
	})

	signedURI, _, err := signer.PresignHTTP(
		context.Background(),
		aws.Credentials{
			AccessKeyID:     accessKey,
			SecretAccessKey: secretKey,
		},
		req,
		"UNSIGNED-PAYLOAD",
		"s3",
		region,
		signingTime,
	)
	if err != nil {
		t.Fatalf("presign request: %v", err)
	}

	signedURL, err := url.Parse(signedURI)
	if err != nil {
		t.Fatalf("parse signed URI: %v", err)
	}

	query := signedURL.Query()
	if opts.rawQueryMutator != nil {
		opts.rawQueryMutator(query)
	}

	return httptest.NewRequest(method, requestPath+"?"+query.Encode(), nil)
}

func testFilerSuccess() *fakeFilerClient {
	return &fakeFilerClient{
		response: &filer_pb.LookupDirectoryEntryResponse{
			Entry: &filer_pb.Entry{Name: "raw-public.plain.zip"},
		},
	}
}

func TestPresignedURL_HappyPath(t *testing.T) {
	cfg := testConfig()
	router, err := NewRouter(cfg, testFilerSuccess())
	if err != nil {
		t.Fatalf("NewRouter() error = %v", err)
	}

	req := buildSignedRequest(t, cfg, http.MethodGet, "/zip/abcdef", signOptions{})
	rec := httptest.NewRecorder()
	router.ServeHTTP(rec, req)

	if rec.Code != http.StatusTemporaryRedirect {
		t.Fatalf("status = %d, want %d; body = %q", rec.Code, http.StatusTemporaryRedirect, rec.Body.String())
	}
}

func TestPresignedURL_Boto3CannedVector(t *testing.T) {
	// Precomputed test vector generated by Python's botocore.auth.S3SigV4QueryAuth
	// (matching NOMAD's StorageRedirects.presign_url):
	//
	// URL: https://nomad-lab.eu/files/zip/abcdef
	// Credentials: key="seaweed-access", secret="seaweed-secret", region="us-east-1"
	// Signing Time: 2026-09-02T16:40:06Z
	// Expires: 900s
	// Generated Signature: 5143c401c13ea76327d0fe339e7c0b020d7f8d2d251e5d63aa05a71138a4a478

	cannedDate := time.Date(2026, 9, 2, 16, 40, 6, 0, time.UTC)
	mockNow := cannedDate.Add(30 * time.Second) // 30s after signing

	cfg := testConfig()
	router, err := newRouter(cfg, testFilerSuccess(), func() time.Time { return mockNow })
	if err != nil {
		t.Fatalf("newRouter() error = %v", err)
	}

	cannedQuery := url.Values{
		"X-Amz-Algorithm":     {"AWS4-HMAC-SHA256"},
		"X-Amz-Credential":    {"seaweed-access/20260902/us-east-1/s3/aws4_request"},
		"X-Amz-Date":          {"20260902T164006Z"},
		"X-Amz-Expires":       {"900"},
		"X-Amz-SignedHeaders": {"host"},
		"X-Amz-Signature":     {"5143c401c13ea76327d0fe339e7c0b020d7f8d2d251e5d63aa05a71138a4a478"},
	}

	req := httptest.NewRequest(http.MethodGet, "/zip/abcdef?"+cannedQuery.Encode(), nil)
	rec := httptest.NewRecorder()
	router.ServeHTTP(rec, req)

	if rec.Code != http.StatusTemporaryRedirect {
		t.Fatalf("status = %d, want %d; body = %q", rec.Code, http.StatusTemporaryRedirect, rec.Body.String())
	}
}

func TestPresignedURL_Subpath(t *testing.T) {
	cfg := testConfig()
	router, err := NewRouter(cfg, testFilerSuccess())
	if err != nil {
		t.Fatalf("NewRouter() error = %v", err)
	}

	// Subpaths are currently not implemented (returns 501), but must pass presigned verification
	req := buildSignedRequest(t, cfg, http.MethodGet, "/zip/abcdef/raw/data.txt", signOptions{})
	rec := httptest.NewRecorder()
	router.ServeHTTP(rec, req)

	if rec.Code != http.StatusNotImplemented {
		t.Fatalf("status = %d, want %d (Not Implemented); body = %q", rec.Code, http.StatusNotImplemented, rec.Body.String())
	}
}

func TestPresignedURL_TamperingRejections(t *testing.T) {
	cfg := testConfig()
	router, err := NewRouter(cfg, testFilerSuccess())
	if err != nil {
		t.Fatalf("NewRouter() error = %v", err)
	}

	tests := []struct {
		name    string
		signOpt signOptions
		reqPath string
		want    int
	}{
		{
			name: "tampered signature",
			signOpt: signOptions{
				rawQueryMutator: func(q url.Values) {
					sig := q.Get("X-Amz-Signature")
					if len(sig) > 4 {
						q.Set("X-Amz-Signature", "0000"+sig[4:])
					}
				},
			},
			reqPath: "/zip/abcdef",
			want:    http.StatusForbidden,
		},
		{
			name: "wrong secret key",
			signOpt: signOptions{
				secretKey: "wrong-secret-key",
			},
			reqPath: "/zip/abcdef",
			want:    http.StatusForbidden,
		},
		{
			name: "wrong access key in credential",
			signOpt: signOptions{
				accessKey: "wrong-access-key",
			},
			reqPath: "/zip/abcdef",
			want:    http.StatusForbidden,
		},
		{
			name: "tampered expiration parameter",
			signOpt: signOptions{
				rawQueryMutator: func(q url.Values) {
					q.Set("X-Amz-Expires", "3600")
				},
			},
			reqPath: "/zip/abcdef",
			want:    http.StatusForbidden,
		},
		{
			name: "injected unauthorized query parameter",
			signOpt: signOptions{
				rawQueryMutator: func(q url.Values) {
					q.Set("injected_param", "attack")
				},
			},
			reqPath: "/zip/abcdef",
			want:    http.StatusForbidden,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			req := buildSignedRequest(t, cfg, http.MethodGet, tt.reqPath, tt.signOpt)
			rec := httptest.NewRecorder()
			router.ServeHTTP(rec, req)

			if rec.Code != tt.want {
				t.Fatalf("status = %d, want %d; body = %q", rec.Code, tt.want, rec.Body.String())
			}
		})
	}
}

func TestPresignedURL_PathMismatch(t *testing.T) {
	cfg := testConfig()
	router, err := NewRouter(cfg, testFilerSuccess())
	if err != nil {
		t.Fatalf("NewRouter() error = %v", err)
	}

	// Sign for upload 'abcdef', but send request to 'uvwxyz'
	req := buildSignedRequest(t, cfg, http.MethodGet, "/zip/abcdef", signOptions{})
	tamperedReq := httptest.NewRequest(http.MethodGet, "/zip/uvwxyz?"+req.URL.RawQuery, nil)

	rec := httptest.NewRecorder()
	router.ServeHTTP(rec, tamperedReq)

	if rec.Code != http.StatusForbidden {
		t.Fatalf("status = %d, want %d; body = %q", rec.Code, http.StatusForbidden, rec.Body.String())
	}
}

func TestPresignedURL_ExpirationAndClockSkew(t *testing.T) {
	cfg := testConfig()
	router, err := NewRouter(cfg, testFilerSuccess())
	if err != nil {
		t.Fatalf("NewRouter() error = %v", err)
	}

	now := time.Now().UTC()

	tests := []struct {
		name    string
		signOpt signOptions
		want    int
	}{
		{
			name: "expired URL",
			signOpt: signOptions{
				signingTime: now.Add(-2 * time.Hour),
				expires:     30 * time.Minute,
			},
			want: http.StatusForbidden,
		},
		{
			name: "future dated beyond skew tolerance",
			signOpt: signOptions{
				signingTime: now.Add(2 * time.Hour),
				expires:     15 * time.Minute,
			},
			want: http.StatusForbidden,
		},
		{
			name: "future dated within clock skew tolerance",
			signOpt: signOptions{
				signingTime: now.Add(5 * time.Minute),
				expires:     15 * time.Minute,
			},
			want: http.StatusTemporaryRedirect,
		},
		{
			name: "invalid negative expiration",
			signOpt: signOptions{
				rawQueryMutator: func(q url.Values) {
					q.Set("X-Amz-Expires", "-10")
				},
			},
			want: http.StatusBadRequest,
		},
		{
			name: "invalid zero expiration",
			signOpt: signOptions{
				rawQueryMutator: func(q url.Values) {
					q.Set("X-Amz-Expires", "0")
				},
			},
			want: http.StatusBadRequest,
		},
		{
			name: "expiration exceeding 7 days",
			signOpt: signOptions{
				rawQueryMutator: func(q url.Values) {
					q.Set("X-Amz-Expires", "604801")
				},
			},
			want: http.StatusBadRequest,
		},
		{
			name: "non-numeric expiration",
			signOpt: signOptions{
				rawQueryMutator: func(q url.Values) {
					q.Set("X-Amz-Expires", "not-a-number")
				},
			},
			want: http.StatusBadRequest,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			req := buildSignedRequest(t, cfg, http.MethodGet, "/zip/abcdef", tt.signOpt)
			rec := httptest.NewRecorder()
			router.ServeHTTP(rec, req)

			if rec.Code != tt.want {
				t.Fatalf("status = %d, want %d; body = %q", rec.Code, tt.want, rec.Body.String())
			}
		})
	}
}

func TestPresignedURL_MalformedParameters(t *testing.T) {
	cfg := testConfig()
	router, err := NewRouter(cfg, testFilerSuccess())
	if err != nil {
		t.Fatalf("NewRouter() error = %v", err)
	}

	tests := []struct {
		name    string
		signOpt signOptions
		want    int
	}{
		{
			name: "missing X-Amz-Algorithm",
			signOpt: signOptions{
				rawQueryMutator: func(q url.Values) {
					q.Del("X-Amz-Algorithm")
				},
			},
			want: http.StatusBadRequest,
		},
		{
			name: "unsupported X-Amz-Algorithm",
			signOpt: signOptions{
				rawQueryMutator: func(q url.Values) {
					q.Set("X-Amz-Algorithm", "AWS2-HMAC-SHA1")
				},
			},
			want: http.StatusBadRequest,
		},
		{
			name: "missing X-Amz-Signature",
			signOpt: signOptions{
				rawQueryMutator: func(q url.Values) {
					q.Del("X-Amz-Signature")
				},
			},
			want: http.StatusBadRequest,
		},
		{
			name: "missing X-Amz-SignedHeaders",
			signOpt: signOptions{
				rawQueryMutator: func(q url.Values) {
					q.Del("X-Amz-SignedHeaders")
				},
			},
			want: http.StatusBadRequest,
		},
		{
			name: "unsupported X-Amz-SignedHeaders",
			signOpt: signOptions{
				rawQueryMutator: func(q url.Values) {
					q.Set("X-Amz-SignedHeaders", "host;x-custom-header")
				},
			},
			want: http.StatusBadRequest,
		},
		{
			name: "missing X-Amz-Date",
			signOpt: signOptions{
				rawQueryMutator: func(q url.Values) {
					q.Del("X-Amz-Date")
				},
			},
			want: http.StatusBadRequest,
		},
		{
			name: "malformed X-Amz-Date",
			signOpt: signOptions{
				rawQueryMutator: func(q url.Values) {
					q.Set("X-Amz-Date", "2026-09-02T12:00:00Z")
				},
			},
			want: http.StatusBadRequest,
		},
		{
			name: "missing X-Amz-Credential",
			signOpt: signOptions{
				rawQueryMutator: func(q url.Values) {
					q.Del("X-Amz-Credential")
				},
			},
			want: http.StatusBadRequest,
		},
		{
			name: "malformed X-Amz-Credential too few parts",
			signOpt: signOptions{
				rawQueryMutator: func(q url.Values) {
					q.Set("X-Amz-Credential", "seaweed-access/20260902/us-east-1")
				},
			},
			want: http.StatusBadRequest,
		},
		{
			name: "malformed X-Amz-Credential not aws4_request",
			signOpt: signOptions{
				rawQueryMutator: func(q url.Values) {
					q.Set("X-Amz-Credential", "seaweed-access/20260902/us-east-1/s3/not_aws4")
				},
			},
			want: http.StatusBadRequest,
		},
		{
			name: "malformed X-Amz-Credential wrong service",
			signOpt: signOptions{
				rawQueryMutator: func(q url.Values) {
					q.Set("X-Amz-Credential", "seaweed-access/20260902/us-east-1/dynamodb/aws4_request")
				},
			},
			want: http.StatusBadRequest,
		},
		{
			name: "malformed X-Amz-Credential date mismatch with X-Amz-Date",
			signOpt: signOptions{
				rawQueryMutator: func(q url.Values) {
					q.Set("X-Amz-Credential", "seaweed-access/19990101/us-east-1/s3/aws4_request")
				},
			},
			want: http.StatusBadRequest,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			req := buildSignedRequest(t, cfg, http.MethodGet, "/zip/abcdef", tt.signOpt)
			rec := httptest.NewRecorder()
			router.ServeHTTP(rec, req)

			if rec.Code != tt.want {
				t.Fatalf("status = %d, want %d; body = %q", rec.Code, tt.want, rec.Body.String())
			}
		})
	}
}

func TestPresignedURL_UnconfiguredPublicEndpoint(t *testing.T) {
	// Create router with unconfigured PublicEndpoint
	cfg := config.Config{}
	router, err := NewRouter(cfg, nil)
	if err != nil {
		t.Fatalf("NewRouter() error = %v", err)
	}

	// Request to /zip/abcdef without publicEndpoint configured should return 500 Internal Server Error
	req := httptest.NewRequest(http.MethodGet, "/zip/abcdef?X-Amz-Algorithm=AWS4-HMAC-SHA256", nil)
	rec := httptest.NewRecorder()
	router.ServeHTTP(rec, req)

	if rec.Code != http.StatusInternalServerError {
		t.Fatalf("status = %d, want %d; body = %q", rec.Code, http.StatusInternalServerError, rec.Body.String())
	}
	if !strings.Contains(rec.Body.String(), "public endpoint not configured") {
		t.Fatalf("expected error message to mention public endpoint, got %q", rec.Body.String())
	}
}
